# Generated by Django 4.2.4 on 2023-08-16 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_employee_position_remove_employee_emp_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='e_mail',
            new_name='email',
        ),
    ]
